# Generated by Django 5.2.1 on 2025-05-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
